# Generated by Django 3.0.6 on 2020-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
