# Generated by Django 3.0.6 on 2020-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSubType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewsubtype_description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewtype_description', models.CharField(max_length=80)),
            ],
        ),
    ]
