# Generated by Django 3.0.6 on 2020-05-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_reviewsubtype_reviewtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsubtype',
            old_name='reviewsubtype_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reviewtype',
            old_name='reviewtype_description',
            new_name='description',
        ),
    ]
