# Generated by Django 3.0.6 on 2020-05-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200519_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser')),
            ],
        ),
    ]
