# Generated by Django 3.0.6 on 2020-05-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewsubtype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.ReviewSubType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='reviewtype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.ReviewType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
