# Generated by Django 3.0.6 on 2020-05-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200520_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewsubtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ReviewSubType', verbose_name='Подтип'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ReviewType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(default='', max_length=80, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
