# Generated by Django 3.0.6 on 2020-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200525_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
